import Link from "next/link";
import type { Metadata } from "next";
import { ArrowRight, BarChart3, Boxes, Building2, Check, CircleDollarSign, Cloud, CreditCard, LayoutGrid, Package, Receipt, ShieldCheck, ShoppingCart, Store, Users2, WifiOff } from "lucide-react";
import { Container } from "@/components/ui/container";
import { Card } from "@/components/ui/card";
import { buttonStyles } from "@/components/ui/button";
import { DownloadCTA } from "@/components/ui/download-cta";
import { OfflineSyncVisual } from "@/components/product/offline-sync-visual";
import { IndustrySelector } from "@/components/industry-selector";
import { Reveal } from "@/components/ui/reveal";
import { siteConfig } from "@/config/site";
import { pricingPlans } from "@/config/pricing";
import { faqItems } from "@/config/faq";
import { buildMetadata } from "@/lib/seo";

export const metadata: Metadata = buildMetadata({ title: "Dira OS — Business Operating System for Modern Businesses", description: siteConfig.description, path: "/" });

const capabilities = [[ShoppingCart, "POS"], [Package, "Inventory"], [CircleDollarSign, "Finance"], [Users2, "Teams"], [Building2, "Branches"], [BarChart3, "Reports"]] as const;

function PhoneMockup() {
  return <div className="relative mx-auto w-full max-w-[24rem] motion-safe:animate-slide-up"><div className="absolute -inset-10 rounded-full bg-primary/15 blur-3xl" /><div className="relative rounded-[2.4rem] border-[7px] border-slate-900 bg-slate-950 p-2 shadow-[0_28px_80px_rgba(15,23,42,0.28)] dark:border-slate-700"><div className="overflow-hidden rounded-[1.9rem] bg-background"><div className="flex items-center justify-between bg-slate-950 px-5 py-3 text-[10px] text-white"><span>9:41</span><span className="h-1.5 w-12 rounded-full bg-white/20" /><span>● ●</span></div><div className="space-y-4 p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-medium uppercase tracking-[0.2em] text-muted">Good morning</p><p className="mt-1 text-lg font-semibold">Your business</p></div><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary text-white"><LayoutGrid className="h-4 w-4" /></div></div><div className="rounded-2xl bg-slate-950 p-4 text-white"><div className="flex items-center justify-between text-[10px] text-slate-300"><span>Revenue today</span><span className="text-emerald-300">+12.4%</span></div><p className="mt-2 text-2xl font-semibold">KES 84,200</p><div className="mt-4 flex h-12 items-end gap-1.5">{[20, 34, 25, 46, 38, 58, 50, 72, 64, 86, 72, 92].map((height, i) => <span key={i} className="flex-1 rounded-t bg-gradient-to-t from-primary to-cyan-300" style={{ height: `${height}%` }} />)}</div></div><div className="grid grid-cols-2 gap-2"><div className="rounded-2xl border border-border/70 bg-card p-3"><Receipt className="h-4 w-4 text-primary" /><p className="mt-3 text-xl font-semibold">126</p><p className="text-[10px] text-muted">Sales</p></div><div className="rounded-2xl border border-border/70 bg-card p-3"><Boxes className="h-4 w-4 text-primary" /><p className="mt-3 text-xl font-semibold">06</p><p className="text-[10px] text-muted">Low stock</p></div></div><div className="flex items-center gap-2 rounded-2xl border border-emerald-500/20 bg-emerald-500/10 p-3 text-xs text-emerald-700 dark:text-emerald-300"><Cloud className="h-4 w-4" /> Synced just now</div></div></div></div><div className="absolute -right-5 top-20 hidden rounded-2xl border border-border/70 bg-card p-3 shadow-lg sm:block"><p className="text-[10px] text-muted">Recent sale</p><p className="mt-1 text-sm font-semibold">+ KES 4,850</p></div><div className="absolute -left-8 bottom-20 hidden rounded-2xl border border-border/70 bg-card p-3 shadow-lg sm:block"><p className="text-[10px] text-muted">Connection</p><p className="mt-1 flex items-center gap-1.5 text-sm font-semibold"><span className="h-2 w-2 rounded-full bg-emerald-500" /> Synced</p></div></div>;
}

const showcase = [["01", "POS", "Sell faster. Keep the counter moving.", "Fast checkout, product search, receipts and payment handling in one focused flow.", CreditCard], ["02", "Inventory", "Know what is available before it becomes a problem.", "Track products, stock levels, barcode lookups and low-stock awareness.", Package], ["03", "Finance", "Understand where your money is going.", "Keep sales, expenses, collections and balances in view.", CircleDollarSign], ["04", "Team", "Give your team the access they need.", "Manage employees, roles and branch access with clarity.", ShieldCheck], ["05", "Branches", "Manage multiple locations from one system.", "Stay connected across the business as your operations expand.", Store], ["06", "Reports", "Turn business activity into clear insights.", "See performance summaries and trends without digging through tools.", BarChart3]] as const;

export default function HomePage() {
  const organizationSchema = { "@context": "https://schema.org", "@type": "Organization", name: siteConfig.siteName, url: siteConfig.websiteUrl, description: siteConfig.description };
  const softwareSchema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: siteConfig.siteName, applicationCategory: "BusinessApplication", operatingSystem: "Android" };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareSchema) }} />
    <section className="overflow-hidden border-b border-border/60 py-14 sm:py-20 lg:py-24"><Container><div className="grid items-center gap-12 lg:grid-cols-[0.85fr_1.15fr]"><div className="max-w-xl"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-primary">Business Operating System</p><h1 className="mt-5 text-balance text-[clamp(3.25rem,7vw,6.5rem)] font-semibold leading-[0.88] tracking-[-0.065em]">Run your business.<br /><span className="text-primary">Even when the internet doesn&apos;t.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-muted sm:text-lg">Sales, inventory, finance, teams and branches — connected in one simple business operating system.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><DownloadCTA label="Start Free Trial" className="sm:min-w-[10.5rem]" /><Link href="#product" className={buttonStyles("secondary", "sm:min-w-[10.5rem]")}>Explore Dira OS</Link></div><div className="mt-5 flex items-center gap-2 text-xs text-muted"><Check className="h-4 w-4 text-primary" /> Set up your business in one place</div></div><PhoneMockup /></div></Container></section>
    <section className="border-b border-border/60 bg-card/35"><Container><div className="grid grid-cols-2 divide-x divide-y divide-border/60 sm:grid-cols-3 sm:divide-y-0 lg:grid-cols-6">{capabilities.map(([Icon, label]) => <div key={label} className="flex items-center justify-center gap-2 px-3 py-5 text-xs font-semibold text-muted"><Icon className="h-4 w-4 text-primary" />{label}</div>)}</div></Container></section>
    <section id="product" className="py-16 sm:py-20"><Container><div className="grid items-end gap-8 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-primary">One connected system</p><h2 className="mt-4 max-w-xl text-4xl font-semibold leading-tight tracking-[-0.045em] sm:text-5xl">One system.<br />Everything connected.</h2></div><p className="max-w-lg text-sm leading-7 text-muted">Dira OS brings the essential parts of running your business together — so you can spend less time managing tools and more time managing your business.</p></div><div className="mt-10 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{capabilities.map(([Icon, label], i) => <div key={label} className="relative rounded-2xl border border-border/70 bg-card p-4 shadow-sm"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-4 w-4" /></div><p className="mt-4 text-sm font-semibold">{label}</p><p className="mt-1 text-[11px] text-muted">Connected by Dira OS</p>{i < 5 ? <ArrowRight className="absolute -right-3 top-1/2 z-10 hidden h-5 w-5 rounded-full bg-background p-1 text-primary lg:block" /> : null}</div>)}</div></Container></section>
    <section className="bg-slate-950 py-16 text-white sm:py-20"><Container><div className="grid items-center gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-cyan-300">Signature reliability</p><h2 className="mt-4 text-4xl font-semibold leading-tight tracking-[-0.045em] sm:text-5xl">Your business shouldn&apos;t stop because the internet did.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-slate-300">Dira OS keeps critical business operations available when connectivity is unreliable, then synchronizes your data when the connection returns.</p></div><OfflineSyncVisual /></div></Container></section>
    <section className="py-16 sm:py-20"><Container><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-primary">Product showcase</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.045em] sm:text-5xl">Everything your business needs.<br />Right where you need it.</h2></div><Link href="/features" className={buttonStyles("secondary")}>See all features <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-10 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{showcase.map(([number, title, heading, description, Icon]) => <Reveal key={number}><Card className="group p-5 transition hover:-translate-y-1 hover:border-primary/30"><div className="flex items-center justify-between"><span className="text-xs font-semibold tracking-[0.2em] text-primary">{number}</span><Icon className="h-5 w-5 text-primary transition group-hover:scale-110" /></div><p className="mt-8 text-xs font-semibold uppercase tracking-[0.18em] text-muted">{title}</p><h3 className="mt-2 text-xl font-semibold tracking-tight">{heading}</h3><p className="mt-2 text-sm leading-6 text-muted">{description}</p><div className="mt-5 flex h-16 items-end gap-1 rounded-xl border border-border/60 bg-background/70 p-3">{[28, 42, 36, 64, 52, 74, 62, 88].map((height, i) => <span key={i} className="flex-1 rounded-sm bg-gradient-to-t from-primary/30 to-primary" style={{ height: `${height}%` }} />)}</div></Card></Reveal>)}</div></Container></section>
    <section className="border-y border-border/60 bg-card/30 py-16 sm:py-20"><Container><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-primary">Solutions</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.045em] sm:text-5xl">One OS. Built around your business.</h2></div><div className="mt-10"><IndustrySelector /></div></Container></section>
    <section className="py-16 sm:py-20"><Container><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-primary">Why Dira OS</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.045em] sm:text-5xl">Built for the way businesses actually operate.</h2></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[LayoutGrid, "One system", "Everything important in one place."], [WifiOff, "Works offline", "Keep critical operations moving."], [BarChart3, "Clear visibility", "Understand sales, stock and performance."], [Building2, "Ready to grow", "Add staff and branches as you expand."]].map(([Icon, title, body]) => <Card key={title as string} className="p-5"><Icon className="h-5 w-5 text-primary" /><h3 className="mt-6 font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted">{body as string}</p></Card>)}</div></Container></section>
    <section className="bg-slate-950 py-16 text-white sm:py-20"><Container><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-cyan-300">Pricing</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.045em] sm:text-5xl">Start simple.<br />Scale when you need to.</h2><p className="mt-4 text-sm text-slate-300"><span className="font-semibold text-white">1 MONTH FREE</span> · No card required.</p></div><Link href="/pricing" className={buttonStyles("secondary", "border-white/20 bg-white/10 text-white hover:bg-white/15")}>Compare plans <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{pricingPlans.map((plan) => <Card key={plan.name} className={`border-white/10 bg-white/[0.06] p-5 text-white ${plan.recommended ? "ring-1 ring-cyan-300/70" : ""}`}><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-300">{plan.name}</p>{plan.recommended ? <span className="text-[10px] text-cyan-200">Recommended</span> : null}</div><p className="mt-5 text-2xl font-semibold">{plan.price}</p><p className="mt-1 text-xs text-slate-300">{plan.note}</p><Link href="/download" className="mt-6 inline-flex text-xs font-semibold text-white hover:text-cyan-200">Start free trial <ArrowRight className="ml-1 h-3.5 w-3.5" /></Link></Card>)}</div></Container></section>
    <section className="py-16 sm:py-20"><Container><div className="grid items-center gap-10 rounded-3xl border border-border/70 bg-card p-6 shadow-sm sm:p-10 lg:grid-cols-[1fr_auto]"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-primary">Dira OS on Android</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.045em]">Your business.<br />In your pocket.</h2><p className="mt-4 max-w-lg text-sm leading-7 text-muted">Take Dira OS with you and manage your business wherever you work.</p></div><div className="flex flex-wrap gap-3"><DownloadCTA label="Get Dira OS" /><Link href="/download" className={buttonStyles("secondary")}>Learn more</Link></div></div></Container></section>
    <section className="border-t border-border/60 py-16 sm:py-20"><Container><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-primary">FAQ</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.045em]">Quick answers.</h2></div><div className="mx-auto mt-8 max-w-3xl space-y-3">{faqItems.slice(0, 6).map((item) => <details key={item.question} className="group rounded-2xl border border-border/70 bg-card p-5"><summary className="cursor-pointer list-none text-sm font-semibold">{item.question}<span className="float-right text-primary">+</span></summary><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">{item.answer}</p></details>)}</div></Container></section>
    <section className="pb-16 sm:pb-20"><Container><div className="rounded-3xl bg-gradient-to-br from-primary to-cyan-500 p-8 text-white sm:p-12"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-white/75">Start with clarity</p><h2 className="mt-4 max-w-2xl text-4xl font-semibold tracking-[-0.045em] sm:text-5xl">Run your business with clarity.</h2><p className="mt-4 text-sm text-white/80">Sales. Stock. Finance. Teams. One connected operating system.</p><div className="mt-7 flex flex-wrap gap-3"><DownloadCTA label="Start Your Free Month" className="bg-white text-slate-950 hover:bg-white/90" /><Link href="/features" className={buttonStyles("secondary", "border-white/30 bg-white/10 text-white hover:bg-white/20")}>Explore Dira OS</Link></div></div></Container></section>
  </>;
}
