import Link from "next/link";
import type { Metadata } from "next";
import { ArrowRight, BarChart3, Building2, Check, CircleDollarSign, Cloud, CreditCard, LayoutGrid, Package, Receipt, ShieldCheck, ShoppingCart, Store, Users2, WifiOff } from "lucide-react";
import { Container } from "@/components/ui/container";
import { Card } from "@/components/ui/card";
import { buttonStyles } from "@/components/ui/button";
import { DownloadCTA } from "@/components/ui/download-cta";
import { OfflineSyncVisual } from "@/components/product/offline-sync-visual";
import { IndustrySelector } from "@/components/industry-selector";
import { HomeFaq } from "@/components/home-faq";
import { siteConfig } from "@/config/site";
import { pricingPlans } from "@/config/pricing";
import { faqItems } from "@/config/faq";
import { buildMetadata } from "@/lib/seo";

export const metadata: Metadata = buildMetadata({ title: "Dira OS — Business Operating System for Modern Businesses", description: "Dira OS is an all-in-one business operating system for managing sales, inventory, finance, teams, branches and everyday business operations.", path: "/" });

const capabilities = [[ShoppingCart, "POS"], [Package, "Inventory"], [CircleDollarSign, "Finance"], [Users2, "Teams"], [Building2, "Branches"], [BarChart3, "Reports"]] as const;

function DashboardScreen() {
  return <div className="rounded-[1.35rem] border border-slate-200/80 bg-white p-3 text-slate-950 shadow-[0_22px_60px_rgba(15,23,42,0.12)]"><div className="flex items-center justify-between border-b border-slate-100 pb-3"><div className="flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-blue-600 text-white"><LayoutGrid className="h-3.5 w-3.5" /></span><span className="text-[11px] font-semibold">Overview</span></div><span className="rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-semibold text-emerald-700">● Synced</span></div><div className="grid grid-cols-3 gap-2 py-3"><div className="rounded-xl bg-slate-50 p-2"><p className="text-[8px] text-slate-500">Revenue</p><p className="mt-1 text-sm font-bold">KES 84,200</p><p className="mt-1 text-[8px] font-semibold text-emerald-600">+12.4%</p></div><div className="rounded-xl bg-slate-50 p-2"><p className="text-[8px] text-slate-500">Sales</p><p className="mt-1 text-sm font-bold">126</p><p className="mt-1 text-[8px] text-slate-500">Today</p></div><div className="rounded-xl bg-slate-50 p-2"><p className="text-[8px] text-slate-500">Low stock</p><p className="mt-1 text-sm font-bold">06</p><p className="mt-1 text-[8px] text-amber-600">Review</p></div></div><div className="rounded-xl border border-slate-100 p-3"><div className="flex items-center justify-between"><p className="text-[9px] font-semibold">Revenue trend</p><p className="text-[8px] text-slate-400">This week</p></div><div className="mt-3 flex h-20 items-end gap-1.5">{[26, 38, 30, 52, 45, 68, 58, 82, 72, 90].map((height, i) => <span key={i} className="flex-1 rounded-t bg-gradient-to-t from-blue-600 to-cyan-400 motion-safe:animate-bar-rise" style={{ height: `${height}%`, animationDelay: `${i * 40}ms` }} />)}</div></div><div className="mt-2 flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2"><div className="flex items-center gap-2"><Receipt className="h-3.5 w-3.5 text-blue-600" /><span className="text-[9px] font-medium">Recent transactions</span></div><span className="text-[9px] font-semibold text-blue-600">View all</span></div></div>;
}

function PhoneMockup() {
  return <div className="relative mx-auto w-full max-w-[25rem] motion-safe:animate-slide-up"><div className="absolute -inset-12 rounded-full bg-blue-500/15 blur-3xl" /><div className="absolute -right-8 top-20 z-10 hidden rounded-2xl border border-slate-200 bg-white p-3 shadow-[0_18px_50px_rgba(15,23,42,0.14)] sm:block"><p className="text-[10px] text-slate-500">Today&apos;s revenue</p><p className="mt-1 text-sm font-bold text-slate-950">KES 84,200</p><p className="mt-1 text-[10px] font-semibold text-emerald-600">↑ 12.4%</p></div><div className="absolute -left-9 bottom-28 z-10 hidden rounded-2xl border border-slate-200 bg-white p-3 shadow-[0_18px_50px_rgba(15,23,42,0.14)] sm:block"><p className="text-[10px] text-slate-500">Connection</p><p className="mt-1 flex items-center gap-1.5 text-sm font-bold text-slate-950"><span className="h-2 w-2 rounded-full bg-emerald-500" /> Synced</p></div><div className="relative rounded-[2.6rem] border-[8px] border-slate-950 bg-slate-950 p-2 shadow-[0_34px_90px_rgba(15,23,42,0.3)]"><div className="overflow-hidden rounded-[2rem] bg-slate-50"><div className="flex items-center justify-between bg-slate-950 px-5 py-3 text-[10px] text-white"><span>9:41</span><span className="h-1.5 w-12 rounded-full bg-white/20" /><span>● ●</span></div><div className="space-y-4 p-4"><div className="flex items-center justify-between"><div><p className="text-[9px] font-medium uppercase tracking-[0.18em] text-slate-500">Good morning</p><p className="mt-1 text-base font-bold text-slate-950">Your business</p></div><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-600 text-white"><LayoutGrid className="h-4 w-4" /></div></div><DashboardScreen /><div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-2.5 text-[10px] font-semibold text-emerald-700"><Cloud className="h-3.5 w-3.5" /> Your data is synced</div></div></div></div></div>;
}

function ProductCanvas() {
  return <div className="relative rounded-[1.75rem] border border-slate-800 bg-slate-950 p-3 shadow-[0_30px_90px_rgba(2,6,23,0.35)]"><div className="flex items-center justify-between border-b border-white/10 px-2 pb-3 text-white"><div className="flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-blue-500"><LayoutGrid className="h-3.5 w-3.5" /></span><span className="text-xs font-semibold">Dira OS</span></div><span className="text-[10px] text-slate-400">Main branch · Today</span></div><div className="grid gap-3 p-2 sm:grid-cols-[0.72fr_1.28fr]"><div className="space-y-2"><div className="rounded-xl bg-white/[0.08] p-3 text-white"><p className="text-[10px] text-slate-400">Today&apos;s revenue</p><p className="mt-2 text-xl font-bold">KES 84,200</p><p className="mt-1 text-[10px] text-emerald-300">↑ 12.4% from yesterday</p></div>{[["Sales", "126"], ["Products", "482"], ["Team", "08"]].map(([label, value]) => <div key={label} className="flex items-center justify-between rounded-xl border border-white/10 px-3 py-2.5 text-[10px] text-slate-300"><span>{label}</span><span className="font-semibold text-white">{value}</span></div>)}</div><div className="rounded-xl bg-white p-3"><div className="flex items-center justify-between"><p className="text-[10px] font-semibold text-slate-900">Revenue trend</p><span className="text-[9px] text-slate-400">Last 7 days</span></div><div className="mt-8 flex h-32 items-end gap-2">{[35, 48, 42, 66, 58, 78, 70, 92, 82].map((height, i) => <span key={i} className="flex-1 rounded-t bg-gradient-to-t from-blue-600 to-cyan-300" style={{ height: `${height}%` }} />)}</div><div className="mt-3 flex items-center justify-between text-[9px] text-slate-400"><span>Mon</span><span>Today</span></div></div></div></div>;
}

const showcase = [["01", "POS", "Sell faster. Keep the counter moving.", "Fast checkout, barcode/SKU lookup, discounts and receipts in one focused flow.", CreditCard], ["02", "Inventory", "Know what is available before it becomes a problem.", "See products, stock levels, low-stock indicators and inventory activity.", Package], ["03", "Finance", "Understand where your money is going.", "Keep income, expenses, balances and financial summaries in view.", CircleDollarSign], ["04", "Team", "Give your team the access they need.", "Manage staff, roles and permissions with clarity.", ShieldCheck], ["05", "Branches", "Manage multiple locations from one system.", "Stay connected across the business as your operations expand.", Store], ["06", "Reports", "Turn business activity into clear insights.", "Read revenue trends, sales performance, expenses and stock at a glance.", BarChart3]] as const;

export default function HomePage() {
  const organizationSchema = { "@context": "https://schema.org", "@type": "Organization", name: siteConfig.siteName, url: siteConfig.websiteUrl, description: siteConfig.description };
  const softwareSchema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: siteConfig.siteName, applicationCategory: "BusinessApplication", operatingSystem: "Android" };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareSchema) }} />
    <section className="hero-grid overflow-hidden border-b border-border/60"><Container><div className="grid items-center gap-14 py-16 sm:py-20 lg:grid-cols-[0.78fr_1.22fr] lg:py-24"><div className="max-w-xl"><p className="eyebrow">Business operating system</p><h1 className="mt-5 text-balance text-[clamp(2.8rem,5vw,4.5rem)] font-bold leading-[1.02] tracking-[-0.045em]">Run your business.<br /><span className="text-primary">Even when the internet doesn&apos;t.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-muted sm:text-lg">Sales, inventory, finance, teams and branches — connected in one simple business operating system.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><DownloadCTA label="Start Free Trial" className="sm:min-w-[10.5rem]" /><Link href="#product" className={buttonStyles("secondary", "sm:min-w-[10.5rem]")}>Explore Dira OS <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-5 flex items-center gap-2 text-xs text-muted"><Check className="h-4 w-4 text-primary" /> 1 month free · No card required</div></div><PhoneMockup /></div></Container></section>
    <section className="border-b border-border/60 bg-card/50"><Container><div className="grid grid-cols-2 divide-x divide-y divide-border/60 sm:grid-cols-3 sm:divide-y-0 lg:grid-cols-6">{capabilities.map(([Icon, label]) => <div key={label} className="flex items-center justify-center gap-2 px-3 py-5 text-xs font-semibold text-muted"><Icon className="h-4 w-4 text-primary" />{label}</div>)}</div></Container></section>
    <section id="product" className="section-pad"><Container><div className="grid items-end gap-8 lg:grid-cols-[0.78fr_1.22fr]"><div><p className="eyebrow">One connected system</p><h2 className="section-title mt-4">One system.<br />Everything connected.</h2></div><p className="max-w-lg text-base leading-7 text-muted">Dira OS brings the essential parts of running your business together — so you can spend less time managing tools and more time managing your business.</p></div><div className="mt-12 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{capabilities.map(([Icon, label], i) => <div key={label} className="relative rounded-2xl border border-border/70 bg-card p-4 transition duration-200 hover:-translate-y-1 hover:border-primary/30 hover:shadow-panel"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-4 w-4" /></div><p className="mt-4 text-sm font-semibold">{label}</p><p className="mt-1 text-[11px] text-muted">Connected by Dira OS</p>{i < 5 ? <ArrowRight className="absolute -right-3 top-1/2 z-10 hidden h-5 w-5 rounded-full bg-background p-1 text-primary lg:block" /> : null}</div>)}</div></Container></section>
    <section className="section-pad bg-slate-950 text-white"><Container><div className="grid items-center gap-12 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="eyebrow text-cyan-300">Product showcase</p><h2 className="section-title mt-4 text-white">Everything your business needs.<br />Right where you need it.</h2><p className="mt-5 max-w-lg text-base leading-7 text-slate-300">A calm command centre for the work that keeps your business moving — from the first sale to the end-of-day report.</p><Link href="/features" className={buttonStyles("secondary", "mt-8 border-white/20 bg-white/10 text-white hover:bg-white/15")}>Explore features <ArrowRight className="h-4 w-4" /></Link></div><ProductCanvas /></div></Container></section>
    <section className="section-pad bg-slate-950 text-white"><Container><div className="grid items-center gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="eyebrow text-cyan-300">Signature reliability</p><h2 className="section-title mt-4 text-white">Your business shouldn&apos;t stop because the internet did.</h2><p className="mt-5 max-w-lg text-base leading-7 text-slate-300">Dira OS keeps critical business operations available when connectivity is unreliable, then synchronizes your data when the connection returns.</p></div><OfflineSyncVisual /></div></Container></section>
    <section className="section-pad"><Container><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Six ways to stay in control</p><h2 className="section-title mt-4">The operating system for everyday work.</h2></div><Link href="/features" className={buttonStyles("secondary")}>See all features <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{showcase.map(([number, title, heading, description, Icon]) => <Card key={number} className="group p-5 transition duration-200 hover:-translate-y-1 hover:border-primary/30 hover:shadow-panel"><div className="flex items-center justify-between"><span className="text-xs font-semibold tracking-[0.2em] text-primary">{number}</span><Icon className="h-5 w-5 text-primary transition group-hover:scale-110" /></div><p className="mt-8 text-xs font-semibold uppercase tracking-[0.18em] text-muted">{title}</p><h3 className="mt-2 text-xl font-semibold tracking-tight">{heading}</h3><p className="mt-2 text-sm leading-6 text-muted">{description}</p><div className="mt-5 flex h-16 items-end gap-1 rounded-xl border border-border/60 bg-background/70 p-3">{[28, 42, 36, 64, 52, 74, 62, 88].map((height, i) => <span key={i} className="flex-1 rounded-sm bg-gradient-to-t from-primary/30 to-primary" style={{ height: `${height}%` }} />)}</div></Card>)}</div></Container></section>
    <section className="border-y border-border/60 bg-card/30 section-pad"><Container><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">Solutions</p><h2 className="section-title mt-4">One OS. Built around your business.</h2></div><div className="mt-10"><IndustrySelector /></div></Container></section>
    <section className="section-pad"><Container><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">Why Dira OS</p><h2 className="section-title mt-4">Built for the way businesses actually operate.</h2></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[LayoutGrid, "One system", "Everything important in one place."], [WifiOff, "Works offline", "Keep critical operations moving."], [BarChart3, "Clear visibility", "Understand sales, stock and performance."], [Building2, "Ready to grow", "Add staff and branches as you expand."]].map(([Icon, title, body]) => <Card key={title as string} className="p-5"><Icon className="h-5 w-5 text-primary" /><h3 className="mt-6 font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted">{body as string}</p></Card>)}</div></Container></section>
    <section className="section-pad bg-slate-950 text-white"><Container><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="eyebrow text-cyan-300">Pricing</p><h2 className="section-title mt-4 text-white">Start simple.<br />Scale when you need to.</h2><p className="mt-4 text-sm text-slate-300"><span className="font-semibold text-white">1 MONTH FREE</span> · No card required.</p></div><Link href="/pricing" className={buttonStyles("secondary", "border-white/20 bg-white/10 text-white hover:bg-white/15")}>Compare plans <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{pricingPlans.map((plan) => <Card key={plan.name} className={`border-white/10 bg-white/[0.06] p-5 text-white ${plan.recommended ? "ring-1 ring-cyan-300/70" : ""}`}><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-300">{plan.name}</p>{plan.recommended ? <span className="text-[10px] text-cyan-200">Recommended</span> : null}</div><p className="mt-5 text-3xl font-bold">{plan.price}</p><p className="mt-1 text-xs text-slate-300">{plan.note}</p><ul className="mt-5 space-y-2 text-xs text-slate-300">{plan.features.slice(0, 3).map((feature) => <li key={feature} className="flex gap-2"><Check className="h-3.5 w-3.5 text-cyan-300" />{feature}</li>)}</ul><Link href="/download" className="mt-6 inline-flex text-xs font-semibold text-white hover:text-cyan-200">Start free trial <ArrowRight className="ml-1 h-3.5 w-3.5" /></Link></Card>)}</div></Container></section>
    <section className="section-pad"><Container><div className="grid items-center gap-10 rounded-3xl border border-border/70 bg-card p-7 shadow-sm sm:p-10 lg:grid-cols-[1fr_0.8fr]"><div><p className="eyebrow">Dira OS on Android</p><h2 className="section-title mt-4">Your business.<br />In your pocket.</h2><p className="mt-4 max-w-lg text-base leading-7 text-muted">Take Dira OS with you and manage your business wherever you work.</p><div className="mt-7 flex flex-wrap gap-3"><DownloadCTA label="Get Dira OS" /><Link href="/download" className={buttonStyles("secondary")}>Learn more</Link></div></div><div className="flex justify-center"><PhoneMockup /></div></div></Container></section>
    <section className="border-t border-border/60 section-pad"><Container><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">FAQ</p><h2 className="section-title mt-4">Quick answers.</h2></div><HomeFaq items={faqItems.slice(0, 8)} /></Container></section>
    <section className="pb-16 sm:pb-20"><Container><div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-blue-700 to-blue-950 p-8 text-white sm:p-12"><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-cyan-400/20 blur-3xl" /><div className="relative"><p className="eyebrow text-cyan-200">Start with clarity</p><h2 className="mt-4 max-w-2xl text-4xl font-bold tracking-[-0.04em] sm:text-5xl">Run your business with clarity.</h2><p className="mt-4 text-base text-blue-100">Sales. Stock. Finance. Teams. One connected operating system.</p><div className="mt-7 flex flex-wrap gap-3"><DownloadCTA label="Start Your Free Month" className="bg-white text-slate-950 hover:bg-white/90" /><Link href="/features" className={buttonStyles("secondary", "border-white/30 bg-white/10 text-white hover:bg-white/20")}>Explore Dira OS</Link></div></div></div></Container></section>
  </>;
}
